# PRCP-1010-InsClaimPred

# Problem Statement

Task 1:-Create a predictive model which will help the insurance marketing team to know which customer will buy the product.

Task 2:-Suggestions to the Insurance market team to make  customers  buy the product.

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive/')

Mounted at /content/drive/

In [3]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [4]:
#importing the dataset

In [6]:
data = pd.read_csv("/content/drive/My Drive/data/train.csv")
data

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

# BASIC CHECKS

In [7]:
data.target.value_counts()

0    573518
1     21694
Name: target, dtype: int64

In [8]:
data.isnull().sum()

id                0
target            0
ps_ind_01         0
ps_ind_02_cat     0
ps_ind_03         0
ps_ind_04_cat     0
ps_ind_05_cat     0
ps_ind_06_bin     0
ps_ind_07_bin     0
ps_ind_08_bin     0
ps_ind_09_bin     0
ps_ind_10_bin     0
ps_ind_11_bin     0
ps_ind_12_bin     0
ps_ind_13_bin     0
ps_ind_14         0
ps_ind_15         0
ps_ind_16_bin     0
ps_ind_17_bin     0
ps_ind_18_bin     0
ps_reg_01         0
ps_reg_02         0
ps_reg_03         0
ps_car_01_cat     0
ps_car_02_cat     0
ps_car_03_cat     0
ps_car_04_cat     0
ps_car_05_cat     0
ps_car_06_cat     0
ps_car_07_cat     0
ps_car_08_cat     0
ps_car_09_cat     0
ps_car_10_cat     0
ps_car_11_cat     0
ps_car_11         0
ps_car_12         0
ps_car_13         0
ps_car_14         0
ps_car_15         0
ps_calc_01        0
ps_calc_02        0
ps_calc_03        0
ps_calc_04        0
ps_calc_05        0
ps_calc_06        0
ps_calc_07        0
ps_calc_08        0
ps_calc_09        0
ps_calc_10        0
ps_calc_11        0
ps_calc_12        0
ps_calc_13        0
ps_calc_14        0
ps_calc_15_bin    0
ps_calc_16_bin    0
ps_calc_17_bin    0
ps_calc_18_bin    0
ps_calc_19_bin    0
ps_calc_20_bin    0
dtype: int64

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595212 entries, 0 to 595211
Data columns (total 59 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              595212 non-null  int64
 1   target          595212 non-null  int64
 2   ps_ind_01       595212 non-null  int64
 3   ps_ind_02_cat   595212 non-null  int64
 4   ps_ind_03       595212 non-null  int64
 5   ps_ind_04_cat   595212 non-null  int64
 6   ps_ind_05_cat   595212 non-null  int64
 7   ps_ind_06_bin   595212 non-null  int64
 8   ps_ind_07_bin   595212 non-null  int64
 9   ps_ind_08_bin   595212 non-null  int64
 10  ps_ind_09_bin   595212 non-null  int64
 11  ps_ind_10_bin   595212 non-null  int64
 12  ps_ind_11_bin   595212 non-null  int64
 13  ps_ind_12_bin   595212 non-null  int64
 14  ps_ind_13_bin   595212 non-null  int64
 15  ps_ind_14       595212 non-null  int64
 16  ps_ind_15       595212 non-null  int64
 17  ps_ind_16_bin   595212 non-null  int64
 18  ps_ind_17_bin   595212 non-null  int64
 19  ps_ind_18_bin   595212 non-null  int64
 20  ps_reg_01       595212 non-null  float64
 21  ps_reg_02       595212 non-null  float64
 22  ps_reg_03       595212 non-null  float64
 23  ps_car_01_cat   595212 non-null  int64
 24  ps_car_02_cat   595212 non-null  int64
 25  ps_car_03_cat   595212 non-null  int64
 26  ps_car_04_cat   595212 non-null  int64
 27  ps_car_05_cat   595212 non-null  int64
 28  ps_car_06_cat   595212 non-null  int64
 29  ps_car_07_cat   595212 non-null  int64
 30  ps_car_08_cat   595212 non-null  int64
 31  ps_car_09_cat   595212 non-null  int64
 32  ps_car_10_cat   595212 non-null  int64
 33  ps_car_11_cat   595212 non-null  int64
 34  ps_car_11       595212 non-null  int64
 35  ps_car_12       595212 non-null  float64
 36  ps_car_13       595212 non-null  float64
 37  ps_car_14       595212 non-null  float64
 38  ps_car_15       595212 non-null  float64
 39  ps_calc_01      595212 non-null  float64
 40  ps_calc_02      595212 non-null  float64
 41  ps_calc_03      595212 non-null  float64
 42  ps_calc_04      595212 non-null  int64
 43  ps_calc_05      595212 non-null  int64
 44  ps_calc_06      595212 non-null  int64
 45  ps_calc_07      595212 non-null  int64
 46  ps_calc_08      595212 non-null  int64
 47  ps_calc_09      595212 non-null  int64
 48  ps_calc_10      595212 non-null  int64
 49  ps_calc_11      595212 non-null  int64
 50  ps_calc_12      595212 non-null  int64
 51  ps_calc_13      595212 non-null  int64
 52  ps_calc_14      595212 non-null  int64
 53  ps_calc_15_bin  595212 non-null  int64
 54  ps_calc_16_bin  595212 non-null  int64
 55  ps_calc_17_bin  595212 non-null  int64
 56  ps_calc_18_bin  595212 non-null  int64
 57  ps_calc_19_bin  595212 non-null  int64
 58  ps_calc_20_bin  595212 non-null  int64
dtypes: float64(10), int64(49)
memory usage: 267.9 MB

In [10]:
data.describe()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,5.952120e+05,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,7.438036e+05,0.036448,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,4.293678e+05,0.187401,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,7.000000e+00,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.719915e+05,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.435475e+05,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1.115549e+06,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1.488027e+06,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# The dataset has unique id values so we can drop the "id" column

In [11]:
data.drop("id",axis=1,inplace=True)
data

,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,2,2,5,1,0,0,1,0,0,...,9,1,5,8,0,1,1,0,0,1
1,0,1,1,7,0,0,0,0,1,0,...,3,1,1,9,0,1,1,0,1,0
2,0,5,4,9,1,0,0,0,1,0,...,4,2,7,7,0,1,1,0,1,0
3,0,0,1,2,0,0,1,0,0,0,...,2,2,4,9,0,0,0,0,0,0
4,0,0,2,0,1,0,1,0,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,0,3,1,10,0,0,0,0,0,1,...,4,1,9,6,0,1,1,0,1,1
595208,0,5,1,3,0,0,0,0,0,1,...,4,1,3,8,1,0,1,0,1,1
595209,0,1,1,10,0,0,1,0,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,0,5,2,3,1,0,0,0,1,0,...,4,1,4,2,0,1,1,1,0,0
595211,0,0,1,8,0,0,1,0,0,0,...,4,4,3,8,0,1,0,0,0,0

# EDA

# Due to privacy concerns, the company has not shared the names of the features. You can skip the EDA part and move directly towards the modelling.

In [12]:
data1=data.drop("target",axis=1)
data1

,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,2,2,5,1,0,0,1,0,0,0,...,9,1,5,8,0,1,1,0,0,1
1,1,1,7,0,0,0,0,1,0,0,...,3,1,1,9,0,1,1,0,1,0
2,5,4,9,1,0,0,0,1,0,0,...,4,2,7,7,0,1,1,0,1,0
3,0,1,2,0,0,1,0,0,0,0,...,2,2,4,9,0,0,0,0,0,0
4,0,2,0,1,0,1,0,0,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,3,1,10,0,0,0,0,0,1,0,...,4,1,9,6,0,1,1,0,1,1
595208,5,1,3,0,0,0,0,0,1,0,...,4,1,3,8,1,0,1,0,1,1
595209,1,1,10,0,0,1,0,0,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,5,2,3,1,0,0,0,1,0,0,...,4,1,4,2,0,1,1,1,0,0
595211,0,1,8,0,0,1,0,0,0,0,...,4,4,3,8,0,1,0,0,0,0

In [13]:
data1.describe()

,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,...,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000,595212.000000
mean,1.900378,1.358943,4.423318,0.416794,0.405188,0.393742,0.257033,0.163921,0.185304,0.000373,...,5.441382,1.441918,2.872288,7.539026,0.122427,0.627840,0.554182,0.287182,0.349024,0.153318
std,1.983789,0.664594,2.699902,0.493311,1.350642,0.488579,0.436998,0.370205,0.388544,0.019309,...,2.332871,1.202963,1.694887,2.746652,0.327779,0.483381,0.497056,0.452447,0.476662,0.360295
min,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# Splitting of the dependent and independent data need to be done

In [14]:
x=data1
y=data.target

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)
x_scaled

array([[ 0.0502179 ,  0.9645855 ,  0.21359383, ..., -0.63472992,
        -0.73222528,  2.34997253],
       [-0.45386836, -0.54009356,  0.95436209, ..., -0.63472992,
         1.36569991, -0.42553689],
       [ 1.56247669,  3.9739436 ,  1.69513035, ..., -0.63472992,
         1.36569991, -0.42553689],
       ...,
       [-0.45386836, -0.54009356,  2.06551448, ..., -0.63472992,
        -0.73222528, -0.42553689],
       [ 1.56247669,  0.9645855 , -0.52717443, ...,  1.57547323,
        -0.73222528, -0.42553689],
       [-0.95795462, -0.54009356,  1.32474622, ..., -0.63472992,
        -0.73222528, -0.42553689]])

In [16]:
data.columns

Index(['target', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03', 'ps_ind_04_cat',
       'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin', 'ps_ind_08_bin',
       'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin', 'ps_ind_12_bin',
       'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15', 'ps_ind_16_bin',
       'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01', 'ps_reg_02', 'ps_reg_03',
       'ps_car_01_cat', 'ps_car_02_cat', 'ps_car_03_cat', 'ps_car_04_cat',
       'ps_car_05_cat', 'ps_car_06_cat', 'ps_car_07_cat', 'ps_car_08_cat',
       'ps_car_09_cat', 'ps_car_10_cat', 'ps_car_11_cat', 'ps_car_11',
       'ps_car_12', 'ps_car_13', 'ps_car_14', 'ps_car_15', 'ps_calc_01',
       'ps_calc_02', 'ps_calc_03', 'ps_calc_04', 'ps_calc_05', 'ps_calc_06',
       'ps_calc_07', 'ps_calc_08', 'ps_calc_09', 'ps_calc_10', 'ps_calc_11',
       'ps_calc_12', 'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin',
       'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin',
       'ps_calc_20_bin'],
      dtype='object')

In [17]:
X=data.loc[:,['ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03',
       'ps_ind_04_cat', 'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15',
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01',
       'ps_reg_02', 'ps_reg_03', 'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat', 'ps_car_11', 'ps_car_12', 'ps_car_13', 'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09',
       'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14',
       'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin',
       'ps_calc_19_bin', 'ps_calc_20_bin']] ## X variable contains all inputs
y=data.target ## y is output

In [18]:
y.value_counts()

0    573518
1     21694
Name: target, dtype: int64

Since the data is imbalanced we need to balance the data by smooting

In [19]:
# Apply SMOTE to balance the data
from imblearn.over_sampling import SMOTE
smote = SMOTE() ## object creation

In [20]:
X_smote, y_smote = smote.fit_resample(x_scaled, y)

In [21]:
from collections import Counter
print("Actual Classes",Counter(y))
print("SMOTE Classes",Counter(y_smote))

Actual Classes Counter({0: 573518, 1: 21694})
SMOTE Classes Counter({0: 573518, 1: 573518})

In [22]:
y_smote.value_counts()

0    573518
1    573518
Name: target, dtype: int64

# Now since the Dependent data is now balanced we can proceed with Training followed by Model Creation .

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_smote,y_smote,test_size=0.2, random_state=24)

# 1.LOGISTIC REGRESSION

Logistic Regression is commonly used to estimate the probability that an instance belongs to a particular class.If the estimated probability is greater than 50% then the model predicts that the instance belongs to that class(called the positive class ,labeled as '1') or else it predict that it does not
(that is it belongs to the negative class ,labeled as 'o' ).This make it a binary classifier

In [ ]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train,y_train)  ## training

LogisticRegression()

In [ ]:
y_pred=clf.predict(X_test)
y_pred

array([0, 1, 1, ..., 0, 1, 0], dtype=int64)

In [ ]:
## evaluating the model created
from sklearn.metrics import accuracy_score,classification_report,f1_score,recall_score
acc=accuracy_score(y_test,y_pred)
acc

0.5877040033477472

In [ ]:
f1=f1_score(y_test,y_pred)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.5849576550089955

In [ ]:
import warnings
warnings.filterwarnings("ignore")
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.59      0.59      0.59    114618
           1       0.59      0.58      0.58    114790

    accuracy                           0.59    229408
   macro avg       0.59      0.59      0.59    229408
weighted avg       0.59      0.59      0.59    229408

# *FOR TRAINING DATA

In [ ]:
y_train_predict=clf.predict(X_train)#passing X_train to predict Y_train
acc_train=accuracy_score(y_train,y_train_predict)#checking accuracy
acc_train

0.5895242952481834

In [ ]:
f1=f1_score(y_train,y_train_predict)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.5867338430074871

In [ ]:
print(classification_report(y_train,y_train_predict))# it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       0.59      0.60      0.59    458900
           1       0.59      0.58      0.59    458728

    accuracy                           0.59    917628
   macro avg       0.59      0.59      0.59    917628
weighted avg       0.59      0.59      0.59    917628

# 2.ARTIFICIAL NEURAL NETWORK (ANN)

In [ ]:
## model creation for testing data 
from sklearn.neural_network import MLPClassifier
model = MLPClassifier( hidden_layer_sizes=(50,3),learning_rate_init=0.1,max_iter=100,random_state=12) 
model.fit(X_train,y_train) ## training the data

# 50 neurons, 3 hidden layers
# learning_rate_init is used to initial learning rate: controls the step-size in updating the weights

MLPClassifier(hidden_layer_sizes=(50, 3), learning_rate_init=0.1, max_iter=100,
              random_state=12)

In [ ]:
y_predict_proba = model.predict_proba(X_test) ## predicting the probability of class
y_predict = model.predict(X_test)
y_predict

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [ ]:
## Evaluating the model creation 
from sklearn.metrics import accuracy_score,confusion_matrix 
print("Test accuracy :",accuracy_score(y_test,y_predict))

Test accuracy : 0.500374877946715

In [ ]:
f1=f1_score(y_test,y_predict)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.6669998082499027

In [ ]:
print(classification_report(y_test,y_predict))# it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       0.00      0.00      0.00    114618
           1       0.50      1.00      0.67    114790

    accuracy                           0.50    229408
   macro avg       0.25      0.50      0.33    229408
weighted avg       0.25      0.50      0.33    229408

In [ ]:
## getting the confusion matrix
c1=pd.crosstab(y_test,y_predict)
c1

col_0        1
target
0       114618
1       114790

# *FOR TRAINING DATA

In [ ]:
y_train_predict=model.predict(X_train)#passing X_train to predict Y_train
acc_train=accuracy_score(y_train,y_train_predict)#checking accuracy
acc_train

0.49990628010479193

In [ ]:
print(classification_report(y_train,y_train_predict))# it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       0.00      0.00      0.00    458900
           1       0.50      1.00      0.67    458728

    accuracy                           0.50    917628
   macro avg       0.25      0.50      0.33    917628
weighted avg       0.25      0.50      0.33    917628

# 3.RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Evaluate the model on the testing set
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,f1_score,recall_score
acc=accuracy_score(y_test,y_pred)
acc

0.9810904589203515

In [ ]:
f1=f1_score(y_test,y_pred)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.9807407144315892

In [ ]:
print(classification_report(y_test,y_pred))# it will give precision,recall,f1 scores and accuracy

              precision    recall  f1-score   support

           0       0.96      1.00      0.98    114618
           1       1.00      0.96      0.98    114790

    accuracy                           0.98    229408
   macro avg       0.98      0.98      0.98    229408
weighted avg       0.98      0.98      0.98    229408

# 4.SVM

In [ ]:
Y=data.target
Y

0         0
1         0
2         0
3         0
4         0
         ..
595207    0
595208    0
595209    0
595210    0
595211    0
Name: target, Length: 595212, dtype: int64

In [ ]:
data

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,0,3,1,10,0,0,0,0,0,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,0,5,1,3,0,0,0,0,0,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,0,1,1,10,0,0,1,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,0,5,2,3,1,0,0,0,1,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,0,1,8,0,0,1,0,0,...,4,4,3,8,0,1,0,0,0,0

In [ ]:
data.drop(["target"],axis=1)

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,2,2,5,1,0,0,1,0,0,...,9,1,5,8,0,1,1,0,0,1
1,9,1,1,7,0,0,0,0,1,0,...,3,1,1,9,0,1,1,0,1,0
2,13,5,4,9,1,0,0,0,1,0,...,4,2,7,7,0,1,1,0,1,0
3,16,0,1,2,0,0,1,0,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,2,0,1,0,1,0,0,0,...,3,1,1,3,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,1488013,3,1,10,0,0,0,0,0,1,...,4,1,9,6,0,1,1,0,1,1
595208,1488016,5,1,3,0,0,0,0,0,1,...,4,1,3,8,1,0,1,0,1,1
595209,1488017,1,1,10,0,0,1,0,0,0,...,3,2,2,6,0,0,1,0,0,0
595210,1488021,5,2,3,1,0,0,0,1,0,...,4,1,4,2,0,1,1,1,0,0
595211,1488027,0,1,8,0,0,1,0,0,0,...,4,4,3,8,0,1,0,0,0,0

In [ ]:
X=data.values
from sklearn.preprocessing import MinMaxScaler
scaled=MinMaxScaler()
X_scaled=scaled.fit_transform(X)
X=pd.DataFrame(X_scaled)
X

,0,1,2,3,4,5,6,7,8,9,...,49,50,51,52,53,54,55,56,57,58
0,0.000000,0.0,0.285714,0.6,0.454545,1.0,0.142857,0.0,1.0,0.0,...,0.473684,0.1,0.384615,0.347826,0.0,1.0,1.0,0.0,0.0,1.0
1,0.000001,0.0,0.142857,0.4,0.636364,0.5,0.142857,0.0,0.0,1.0,...,0.157895,0.1,0.076923,0.391304,0.0,1.0,1.0,0.0,1.0,0.0
2,0.000004,0.0,0.714286,1.0,0.818182,1.0,0.142857,0.0,0.0,1.0,...,0.210526,0.2,0.538462,0.304348,0.0,1.0,1.0,0.0,1.0,0.0
3,0.000006,0.0,0.000000,0.4,0.181818,0.5,0.142857,1.0,0.0,0.0,...,0.105263,0.2,0.307692,0.391304,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000007,0.0,0.000000,0.6,0.000000,1.0,0.142857,1.0,0.0,0.0,...,0.157895,0.1,0.076923,0.130435,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,0.999991,0.0,0.428571,0.4,0.909091,0.5,0.142857,0.0,0.0,0.0,...,0.210526,0.1,0.692308,0.260870,0.0,1.0,1.0,0.0,1.0,1.0
595208,0.999993,0.0,0.714286,0.4,0.272727,0.5,0.142857,0.0,0.0,0.0,...,0.210526,0.1,0.230769,0.347826,1.0,0.0,1.0,0.0,1.0,1.0
595209,0.999993,0.0,0.142857,0.4,0.909091,0.5,0.142857,1.0,0.0,0.0,...,0.157895,0.2,0.153846,0.260870,0.0,0.0,1.0,0.0,0.0,0.0
595210,0.999996,0.0,0.714286,0.6,0.272727,1.0,0.142857,0.0,0.0,1.0,...,0.210526,0.1,0.307692,0.086957,0.0,1.0,1.0,1.0,0.0,0.0
595211,1.000000,0.0,0.000000,0.4,0.727273,0.5,0.142857,1.0,0.0,0.0,...,0.210526,0.4,0.230769,0.347826,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
X

,0,1,2,3,4,5,6,7,8,9,...,49,50,51,52,53,54,55,56,57,58
0,0.000000,0.0,0.285714,0.6,0.454545,1.0,0.142857,0.0,1.0,0.0,...,0.473684,0.1,0.384615,0.347826,0.0,1.0,1.0,0.0,0.0,1.0
1,0.000001,0.0,0.142857,0.4,0.636364,0.5,0.142857,0.0,0.0,1.0,...,0.157895,0.1,0.076923,0.391304,0.0,1.0,1.0,0.0,1.0,0.0
2,0.000004,0.0,0.714286,1.0,0.818182,1.0,0.142857,0.0,0.0,1.0,...,0.210526,0.2,0.538462,0.304348,0.0,1.0,1.0,0.0,1.0,0.0
3,0.000006,0.0,0.000000,0.4,0.181818,0.5,0.142857,1.0,0.0,0.0,...,0.105263,0.2,0.307692,0.391304,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000007,0.0,0.000000,0.6,0.000000,1.0,0.142857,1.0,0.0,0.0,...,0.157895,0.1,0.076923,0.130435,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595207,0.999991,0.0,0.428571,0.4,0.909091,0.5,0.142857,0.0,0.0,0.0,...,0.210526,0.1,0.692308,0.260870,0.0,1.0,1.0,0.0,1.0,1.0
595208,0.999993,0.0,0.714286,0.4,0.272727,0.5,0.142857,0.0,0.0,0.0,...,0.210526,0.1,0.230769,0.347826,1.0,0.0,1.0,0.0,1.0,1.0
595209,0.999993,0.0,0.142857,0.4,0.909091,0.5,0.142857,1.0,0.0,0.0,...,0.157895,0.2,0.153846,0.260870,0.0,0.0,1.0,0.0,0.0,0.0
595210,0.999996,0.0,0.714286,0.6,0.272727,1.0,0.142857,0.0,0.0,1.0,...,0.210526,0.1,0.307692,0.086957,0.0,1.0,1.0,1.0,0.0,0.0
595211,1.000000,0.0,0.000000,0.4,0.727273,0.5,0.142857,1.0,0.0,0.0,...,0.210526,0.4,0.230769,0.347826,0.0,1.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)  # retain the first two principal components
X=pd.DataFrame(pca.fit_transform(X))
X

               0         1
0       1.026211  0.464507
1       0.217045  0.776137
2      -0.071924 -0.664479
3      -0.536713 -0.097402
4      -0.890721 -0.099920
...          ...       ...
595207  0.119713 -0.745350
595208  0.101367 -0.553194
595209 -1.011899 -0.130103
595210 -0.007502 -0.648266
595211 -0.877114 -0.005845

[595212 rows x 2 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X, Y,random_state=3)

In [ ]:
# Support Vector Classifier Model
from sklearn.svm import SVC
svclassifier = SVC() ## base model with default parameters
svclassifier.fit(X_train,Y_train)

SVC()

In [ ]:
# Predict output for X_test

y_hat=svclassifier.predict(X_test)

In [ ]:
## evaluating the model created
from sklearn.metrics import accuracy_score,classification_report,f1_score
acc=accuracy_score(Y_test,y_hat)
acc

0.9640464237952192

In [ ]:
# Calssification report measures the quality of predictions. True Positives, False Positives, True negatives and False Negatives 
# are used to predict the metrics of a classification report 

print(classification_report(Y_test,y_hat))

C:\Users\sagar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sagar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98    143453
           1       0.00      0.00      0.00      5350

    accuracy                           0.96    148803
   macro avg       0.48      0.50      0.49    148803
weighted avg       0.93      0.96      0.95    148803

C:\Users\sagar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
cm1=pd.crosstab(Y_test,y_hat)
cm1

col_0        0
target
0       143453
1         5350

In [ ]:
# F1 score considers both Precision and Recall for evaluating a model
f1=f1_score(Y_test,y_hat)
f1

0.0

# 5.KNN

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score



# Train the KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [36]:
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

# Print accuracy score
print("Accuracy:", accuracy)

Accuracy: 0.788948075045334

In [37]:
f1=f1_score(y_test,y_pred)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.8258362500314751

In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.58      0.73    114618
           1       0.70      1.00      0.83    114790

    accuracy                           0.79    229408
   macro avg       0.85      0.79      0.78    229408
weighted avg       0.85      0.79      0.78    229408

# 6.XGBOOST

In [24]:
import xgboost as xgb
model = xgb.XGBClassifier(n_estimators=1000,max_depth=10,learning_rate=0.01,subsample=0.8,colsample_bytree=0.8,objective='binary:logistic',random_state=42)

In [25]:
model.fit(X_train,y_train,early_stopping_rounds=10,eval_metric='auc',eval_set=[(X_test, y_test)],verbose=True)

[0]	validation_0-auc:0.94052
[1]	validation_0-auc:0.97407
[2]	validation_0-auc:0.97284
[3]	validation_0-auc:0.98037
[4]	validation_0-auc:0.97862
[5]	validation_0-auc:0.97850
[6]	validation_0-auc:0.97666
[7]	validation_0-auc:0.97939
[8]	validation_0-auc:0.97827
[9]	validation_0-auc:0.97708
[10]	validation_0-auc:0.97598
[11]	validation_0-auc:0.97574
[12]	validation_0-auc:0.97556
[13]	validation_0-auc:0.97462

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=42, ...)

In [26]:
model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=1000, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=42, ...)

In [27]:
y_pred1=model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred1)

# Print accuracy score
print("Accuracy:", accuracy)

Accuracy: 0.9547138722276468

In [30]:
from sklearn.metrics import accuracy_score,classification_report,f1_score
f1=f1_score(y_test,y_pred1)
f1                             # F1 score considers both Precision and Recall for evaluating a model

0.9529212907786635

In [32]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.92      0.99      0.96    114618
           1       0.99      0.92      0.95    114790

    accuracy                           0.95    229408
   macro avg       0.96      0.95      0.95    229408
weighted avg       0.96      0.95      0.95    229408

# 7.DECISION TREE

In [ ]:
from sklearn.model_selection import train_test_split


X_train, X_test, Y_train, Y_test = train_test_split(X_smote, Y_smote, test_size=0.25, random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_leaf= 1, min_samples_split= 3, splitter= 'random')#object creation for decision tree  
dt.fit(X_smote, y_smote)
Y_hat=dt.predict(X_test)
Y_hat

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [ ]:
## Evalauting the model
from sklearn.metrics import accuracy_score,classification_report,f1_score    
##Training score
y_train_predict=dt.predict(X_train)
acc_train=accuracy_score(y_train,y_train_predict)
acc_train

0.7311458983559946

In [ ]:
print(classification_report(y_train,y_train_predict))

              precision    recall  f1-score   support

           0       0.79      0.63      0.70    430219
           1       0.69      0.83      0.75    430058

    accuracy                           0.73    860277
   macro avg       0.74      0.73      0.73    860277
weighted avg       0.74      0.73      0.73    860277

In [ ]:
f1=f1_score(y_train,y_train_predict)
f1

0.7548250249373782

In [ ]:
test_acc=accuracy_score(y_test,y_hat)
test_acc

0.6892059185587898

test_f1=f1_score(y_test,y_hat)
test_f1

# EVALUATION MATRIX

In [35]:
MODELS = ['LOGISTIC ', 'ARTIFICIAL NEURAL NETWORK', 'RANDOM FOREST', 'SVM','KNN','XGBoost','DECISION TREE',] 
F1 = [58, 66, 98, 98,73,96,70]
ACCURACY=[59,50,98,96,78,95,73]

# Create dictionary from keys and values
data = {'MODELS': MODELS, 'F1_SCORES': F1,'ACCURACY':ACCURACY}
df = pd.DataFrame(data)

# Print the resulting DataFrame
df

                      MODELS  F1_SCORES  ACCURACY
0                  LOGISTIC          58        59
1  ARTIFICIAL NEURAL NETWORK         66        50
2              RANDOM FOREST         98        98
3                        SVM         98        96
4                        KNN         73        78
5                    XGBoost         96        95
6              DECISION TREE         70        73

# comparing the accuracy among the models we can compute that "RANDOM FOREST" give the best accuracy score for our dataset